# Hamiltonian Adaptive Ternary Tree

## Algorithm 1

$a_j^+ = \frac{1}{2}(m_{2j} - i m_{2j+1})$

$a_j = \frac{1}{2}(m_{2j} + i m_{2j+1})$

$a_j^+a_k = \frac{1}{4}(m_{2j} - i m_{2j+1})(m_{2k} + i m_{2k+1})$

$=\frac{1}{4}(m_{2j}m_{2k} + m_{2j+1}m_{2k+1} + i m_{2j}m_{2k+1} - i m_{2j+1}m_{2k})$


$a_j^+a_k^+a_la_m$
$=\frac{1}{16}(m_{2j}m_{2k} - m_{2j+1}m_{2k+1} - i m_{2j}m_{2k+1} - i m_{2j+1}m_{2k})(m_{2l}m_{2m} - m_{2l+1}m_{2m+1} + i m_{2l}m_{2m+1} + i m_{2l+1}m_{2m})$

In [22]:
import numpy as np

factors = np.array([1, 0.0 - 1j])

In [23]:
factors, np.conj(factors)

(array([1.+0.j, 0.-1.j]), array([1.-0.j, 0.+1.j]))

In [25]:
np.kron(factors, np.conj(factors))

array([1.+0.j, 0.+1.j, 0.-1.j, 1.+0.j])

- [ ] Preproccess Fermionic Op to Majorana Op
- [ ] Find pauli weight on qubit I

In [1]:
# from itertools import permutations
# import numpy as np
# majorana_hamiltonain = preprocess(fermionic_hamiltonian)
# U = range(0, 2*n_qubits)
# # i loops over qubits
# for qubit_i in range(0, n_qubits):
#     weight = np.inf
#     selection = (None, None, None)
#     for permutation in permutations(U, 3):
#         pw = pauli_weight(majorana_hamiltonain, permutation, qubit_i)
#         if pw < weight:
#             weight = pw
#             selection = permutation

#     # remove the items from the best selection
#     U.remove(permutation)
#     U.add(node["2n+1+i"])

#     # Simplify majorana operators
#     reduce ???

#     # root node is the last item in U
#     assert len(U) == 1
#     root_node = U.pop()


In [2]:
import pickle
from pathlib import Path

from ferrmion.encode import TernaryTree


def water_integrals():
    folder = Path("")
    with open(folder.joinpath("./ones.pkl"), "rb") as file:
        ones = pickle.load(file)

    with open(folder.joinpath("./twos.pkl"), "rb") as file:
        twos = pickle.load(file)
    return (ones, twos)


tree = TernaryTree(14)

In [3]:
ones, twos = water_integrals()

$=\frac{1}{4}(m_{2j}m_{2k} + m_{2j+1}m_{2k+1} + i m_{2j}m_{2k+1} - i m_{2j+1}m_{2k})$

In [ ]:
import numpy as np


def fermion_to_majorana(ones, twos):
    n_modes = ones.shape[0]
    majorana_ones = np.zeros((2 * n_modes, 2 * n_modes), dtype=np.complex64)
    majorana_ones.shape
    # first term
    majorana_ones[::2, ::2] = 0.25 * ones
    # second term
    majorana_ones[1::2, 1::2] = -0.25 * ones
    # third tem
    majorana_ones[::2, 1::2] = 0.25j * ones
    # fourth
    majorana_ones[1::2, ::2] = -0.25j * ones

    majorana_twos = np.zeros(
        (2 * n_modes, 2 * n_modes, 2 * n_modes, 2 * n_modes), dtype=np.complex64
    )
    scale_dict = {(0, 0): 1, (1, 1): -1, (0, 1): -1j, (1, 0): -1j}
    for i in range(2):
        for j in range(2):
            for m in range(2):
                for l in range(2):
                    majorana_twos[i::2, j::2, m::2, l::2] = (
                        scale_dict[(i, j)] * np.conj(scale_dict[(m, l)]) * 1 / 16 * twos
                    )
    return majorana_ones, majorana_twos

$a_j^+a_k^+a_la_m$
$=\frac{1}{16}(m_{2j}m_{2k} - m_{2j+1}m_{2k+1} - i m_{2j}m_{2k+1} - i m_{2j+1}m_{2k})(m_{2l}m_{2m} - m_{2l+1}m_{2m+1} + i m_{2l}m_{2m+1} + i m_{2l+1}m_{2m})$

In [ ]:
test_ones = np.zeros((3, 3))
test_twos = np.zeros((3, 3, 3, 3))
test_ones[0, 0] = 1
test_twos[1, 2, 1, 2] = 2

In [7]:
majorana_ones, majorana_twos = fermion_to_majorana(test_ones, test_twos)

In [10]:
np.where(majorana_ones != 0)

(array([0, 0, 1, 1]), array([0, 1, 0, 1]))

In [11]:
majorana_ones

array([[ 0.25+0.j  ,  0.  +0.25j,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,
         0.  +0.j  ],
       [ 0.  -0.25j, -0.25+0.j  ,  0.  -0.j  , -0.  +0.j  ,  0.  -0.j  ,
        -0.  +0.j  ],
       [ 0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,
         0.  +0.j  ],
       [ 0.  -0.j  , -0.  +0.j  ,  0.  -0.j  , -0.  +0.j  ,  0.  -0.j  ,
        -0.  +0.j  ],
       [ 0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,
         0.  +0.j  ],
       [ 0.  -0.j  , -0.  +0.j  ,  0.  -0.j  , -0.  +0.j  ,  0.  -0.j  ,
        -0.  +0.j  ]], dtype=complex64)

In [12]:
majorana_ones *= -1 * (1 - np.eye(6))
majorana_ones

array([[-0.+0.j  , -0.-0.25j, -0.+0.j  , -0.+0.j  , -0.+0.j  , -0.+0.j  ],
       [ 0.+0.25j,  0.-0.j  ,  0.+0.j  ,  0.-0.j  ,  0.+0.j  ,  0.-0.j  ],
       [-0.+0.j  , -0.+0.j  , -0.+0.j  , -0.+0.j  , -0.+0.j  , -0.+0.j  ],
       [ 0.+0.j  ,  0.-0.j  ,  0.+0.j  ,  0.-0.j  ,  0.+0.j  ,  0.-0.j  ],
       [-0.+0.j  , -0.+0.j  , -0.+0.j  , -0.+0.j  , -0.+0.j  , -0.+0.j  ],
       [ 0.+0.j  ,  0.-0.j  ,  0.+0.j  ,  0.-0.j  ,  0.+0.j  ,  0.-0.j  ]],
      dtype=complex64)

In [ ]:
constant = 2 * np.trace(majorana_ones)
constant

np.complex64(0j)

In [ ]:
np.einsum("iijk->jk", majorana_twos)
np.einsum("jiik->jk", majorana_twos)
np.einsum("jkii->jk", majorana_twos)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]], dtype=complex64)